package com.adpanshi.cashloan.dispatch.run.mapper;

import com.adpanshi.cashloan.dispatch.run.model.NodeInstance;
import com.adpanshi.cashloan.dispatch.run.model.NodeInstanceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NodeInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    long countByExample(NodeInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int deleteByExample(NodeInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int insert(NodeInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int insertSelective(NodeInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    List<NodeInstance> selectByExample(NodeInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    NodeInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NodeInstance record, @Param("example") NodeInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NodeInstance record, @Param("example") NodeInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NodeInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NodeInstance record);
}