package com.adpanshi.cashloan.dispatch.run.mapper;

import com.adpanshi.cashloan.dispatch.run.model.TaskInstance;
import com.adpanshi.cashloan.dispatch.run.model.TaskInstanceExample;
import com.adpanshi.cashloan.dispatch.run.model.TaskInstanceWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TaskInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    long countByExample(TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int deleteByExample(TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int insert(TaskInstanceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int insertSelective(TaskInstanceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    List<TaskInstanceWithBLOBs> selectByExampleWithBLOBs(TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    List<TaskInstance> selectByExample(TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    TaskInstanceWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskInstanceWithBLOBs record, @Param("example") TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TaskInstanceWithBLOBs record, @Param("example") TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskInstance record, @Param("example") TaskInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskInstanceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TaskInstanceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskInstance record);

    List<TaskInstanceWithBLOBs> findParentTaskInsByTaskInsId(@Param("taskInstanceId") Integer taskInstanceId);

    Integer selectNodeInstId(@Param("taskInstanceId") Integer taskInstanceId);

    Integer selectUserDataId(@Param("taskInstanceId") Integer taskInstanceId);
}