package com.adpanshi.cashloan.dispatch.config.model;

import java.io.Serializable;
import java.util.Date;

public class TaskConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FId
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FNumber
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FName
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FAdapterCode
     *
     * @mbg.generated
     */
    private String adapterCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FDesc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FNodeId
     *
     * @mbg.generated
     */
    private Integer nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FIsSync
     *
     * @mbg.generated
     */
    private Boolean isSync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FIsEnable
     *
     * @mbg.generated
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FIsFinalTask
     *
     * @mbg.generated
     */
    private Boolean isFinalTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FCreateUserId
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FLastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FModifyUserId
     *
     * @mbg.generated
     */
    private Integer modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_conf_task.FIsdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_conf_task
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FId
     *
     * @return the value of cl_conf_task.FId
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FId
     *
     * @param id the value for cl_conf_task.FId
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FNumber
     *
     * @return the value of cl_conf_task.FNumber
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FNumber
     *
     * @param number the value for cl_conf_task.FNumber
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FName
     *
     * @return the value of cl_conf_task.FName
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FName
     *
     * @param name the value for cl_conf_task.FName
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FAdapterCode
     *
     * @return the value of cl_conf_task.FAdapterCode
     *
     * @mbg.generated
     */
    public String getAdapterCode() {
        return adapterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FAdapterCode
     *
     * @param adapterCode the value for cl_conf_task.FAdapterCode
     *
     * @mbg.generated
     */
    public void setAdapterCode(String adapterCode) {
        this.adapterCode = adapterCode == null ? null : adapterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FDesc
     *
     * @return the value of cl_conf_task.FDesc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FDesc
     *
     * @param desc the value for cl_conf_task.FDesc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FNodeId
     *
     * @return the value of cl_conf_task.FNodeId
     *
     * @mbg.generated
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FNodeId
     *
     * @param nodeId the value for cl_conf_task.FNodeId
     *
     * @mbg.generated
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FIsSync
     *
     * @return the value of cl_conf_task.FIsSync
     *
     * @mbg.generated
     */
    public Boolean getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FIsSync
     *
     * @param isSync the value for cl_conf_task.FIsSync
     *
     * @mbg.generated
     */
    public void setIsSync(Boolean isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FIsEnable
     *
     * @return the value of cl_conf_task.FIsEnable
     *
     * @mbg.generated
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FIsEnable
     *
     * @param isEnable the value for cl_conf_task.FIsEnable
     *
     * @mbg.generated
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FIsFinalTask
     *
     * @return the value of cl_conf_task.FIsFinalTask
     *
     * @mbg.generated
     */
    public Boolean getIsFinalTask() {
        return isFinalTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FIsFinalTask
     *
     * @param isFinalTask the value for cl_conf_task.FIsFinalTask
     *
     * @mbg.generated
     */
    public void setIsFinalTask(Boolean isFinalTask) {
        this.isFinalTask = isFinalTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FCreateTime
     *
     * @return the value of cl_conf_task.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FCreateTime
     *
     * @param createTime the value for cl_conf_task.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FCreateUserId
     *
     * @return the value of cl_conf_task.FCreateUserId
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FCreateUserId
     *
     * @param createUserId the value for cl_conf_task.FCreateUserId
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FLastModifyTime
     *
     * @return the value of cl_conf_task.FLastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FLastModifyTime
     *
     * @param lastModifyTime the value for cl_conf_task.FLastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FModifyUserId
     *
     * @return the value of cl_conf_task.FModifyUserId
     *
     * @mbg.generated
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FModifyUserId
     *
     * @param modifyUserId the value for cl_conf_task.FModifyUserId
     *
     * @mbg.generated
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_conf_task.FIsdelete
     *
     * @return the value of cl_conf_task.FIsdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_conf_task.FIsdelete
     *
     * @param isdelete the value for cl_conf_task.FIsdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_conf_task
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskConfig other = (TaskConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAdapterCode() == null ? other.getAdapterCode() == null : this.getAdapterCode().equals(other.getAdapterCode()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getNodeId() == null ? other.getNodeId() == null : this.getNodeId().equals(other.getNodeId()))
            && (this.getIsSync() == null ? other.getIsSync() == null : this.getIsSync().equals(other.getIsSync()))
            && (this.getIsEnable() == null ? other.getIsEnable() == null : this.getIsEnable().equals(other.getIsEnable()))
            && (this.getIsFinalTask() == null ? other.getIsFinalTask() == null : this.getIsFinalTask().equals(other.getIsFinalTask()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_conf_task
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAdapterCode() == null) ? 0 : getAdapterCode().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getNodeId() == null) ? 0 : getNodeId().hashCode());
        result = prime * result + ((getIsSync() == null) ? 0 : getIsSync().hashCode());
        result = prime * result + ((getIsEnable() == null) ? 0 : getIsEnable().hashCode());
        result = prime * result + ((getIsFinalTask() == null) ? 0 : getIsFinalTask().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        return result;
    }
}