package com.adpanshi.cashloan.dispatch.config.model;

import java.io.Serializable;
import java.util.Date;

public class TaskRelationConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FId
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FParentTaskId
     *
     * @mbg.generated
     */
    private Integer parentTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FSonTaskId
     *
     * @mbg.generated
     */
    private Integer sonTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FCreateUserId
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FLastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FModifyUserId
     *
     * @mbg.generated
     */
    private Integer modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_conf_task_relation.FIsdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp_conf_task_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FId
     *
     * @return the value of dp_conf_task_relation.FId
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FId
     *
     * @param id the value for dp_conf_task_relation.FId
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FParentTaskId
     *
     * @return the value of dp_conf_task_relation.FParentTaskId
     *
     * @mbg.generated
     */
    public Integer getParentTaskId() {
        return parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FParentTaskId
     *
     * @param parentTaskId the value for dp_conf_task_relation.FParentTaskId
     *
     * @mbg.generated
     */
    public void setParentTaskId(Integer parentTaskId) {
        this.parentTaskId = parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FSonTaskId
     *
     * @return the value of dp_conf_task_relation.FSonTaskId
     *
     * @mbg.generated
     */
    public Integer getSonTaskId() {
        return sonTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FSonTaskId
     *
     * @param sonTaskId the value for dp_conf_task_relation.FSonTaskId
     *
     * @mbg.generated
     */
    public void setSonTaskId(Integer sonTaskId) {
        this.sonTaskId = sonTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FCreateTime
     *
     * @return the value of dp_conf_task_relation.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FCreateTime
     *
     * @param createTime the value for dp_conf_task_relation.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FCreateUserId
     *
     * @return the value of dp_conf_task_relation.FCreateUserId
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FCreateUserId
     *
     * @param createUserId the value for dp_conf_task_relation.FCreateUserId
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FLastModifyTime
     *
     * @return the value of dp_conf_task_relation.FLastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FLastModifyTime
     *
     * @param lastModifyTime the value for dp_conf_task_relation.FLastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FModifyUserId
     *
     * @return the value of dp_conf_task_relation.FModifyUserId
     *
     * @mbg.generated
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FModifyUserId
     *
     * @param modifyUserId the value for dp_conf_task_relation.FModifyUserId
     *
     * @mbg.generated
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_conf_task_relation.FIsdelete
     *
     * @return the value of dp_conf_task_relation.FIsdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_conf_task_relation.FIsdelete
     *
     * @param isdelete the value for dp_conf_task_relation.FIsdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_conf_task_relation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskRelationConfig other = (TaskRelationConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getParentTaskId() == null ? other.getParentTaskId() == null : this.getParentTaskId().equals(other.getParentTaskId()))
            && (this.getSonTaskId() == null ? other.getSonTaskId() == null : this.getSonTaskId().equals(other.getSonTaskId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_conf_task_relation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getParentTaskId() == null) ? 0 : getParentTaskId().hashCode());
        result = prime * result + ((getSonTaskId() == null) ? 0 : getSonTaskId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        return result;
    }
}