package com.adpanshi.cashloan.dispatch.run.model;

import java.io.Serializable;
import java.util.Date;

public class NodeInstance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FId
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FNodeId
     *
     * @mbg.generated
     */
    private Integer nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FUserDataId
     *
     * @mbg.generated
     */
    private Integer userDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FUserAccount
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FUserIdCard
     *
     * @mbg.generated
     */
    private String userIdCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FUserName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FDeviceFingerprint
     *
     * @mbg.generated
     */
    private String deviceFingerprint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FParamsJson
     *
     * @mbg.generated
     */
    private String paramsJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FStatus
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FCreateUserId
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FLastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FModifyUserId
     *
     * @mbg.generated
     */
    private Integer modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dp_inst_node.FIsdelete
     *
     * @mbg.generated
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FId
     *
     * @return the value of dp_inst_node.FId
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FId
     *
     * @param id the value for dp_inst_node.FId
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FNodeId
     *
     * @return the value of dp_inst_node.FNodeId
     *
     * @mbg.generated
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FNodeId
     *
     * @param nodeId the value for dp_inst_node.FNodeId
     *
     * @mbg.generated
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FUserDataId
     *
     * @return the value of dp_inst_node.FUserDataId
     *
     * @mbg.generated
     */
    public Integer getUserDataId() {
        return userDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FUserDataId
     *
     * @param userDataId the value for dp_inst_node.FUserDataId
     *
     * @mbg.generated
     */
    public void setUserDataId(Integer userDataId) {
        this.userDataId = userDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FUserAccount
     *
     * @return the value of dp_inst_node.FUserAccount
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FUserAccount
     *
     * @param userAccount the value for dp_inst_node.FUserAccount
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FUserIdCard
     *
     * @return the value of dp_inst_node.FUserIdCard
     *
     * @mbg.generated
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FUserIdCard
     *
     * @param userIdCard the value for dp_inst_node.FUserIdCard
     *
     * @mbg.generated
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard == null ? null : userIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FUserName
     *
     * @return the value of dp_inst_node.FUserName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FUserName
     *
     * @param userName the value for dp_inst_node.FUserName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FDeviceFingerprint
     *
     * @return the value of dp_inst_node.FDeviceFingerprint
     *
     * @mbg.generated
     */
    public String getDeviceFingerprint() {
        return deviceFingerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FDeviceFingerprint
     *
     * @param deviceFingerprint the value for dp_inst_node.FDeviceFingerprint
     *
     * @mbg.generated
     */
    public void setDeviceFingerprint(String deviceFingerprint) {
        this.deviceFingerprint = deviceFingerprint == null ? null : deviceFingerprint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FParamsJson
     *
     * @return the value of dp_inst_node.FParamsJson
     *
     * @mbg.generated
     */
    public String getParamsJson() {
        return paramsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FParamsJson
     *
     * @param paramsJson the value for dp_inst_node.FParamsJson
     *
     * @mbg.generated
     */
    public void setParamsJson(String paramsJson) {
        this.paramsJson = paramsJson == null ? null : paramsJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FStatus
     *
     * @return the value of dp_inst_node.FStatus
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FStatus
     *
     * @param status the value for dp_inst_node.FStatus
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FCreateTime
     *
     * @return the value of dp_inst_node.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FCreateTime
     *
     * @param createTime the value for dp_inst_node.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FCreateUserId
     *
     * @return the value of dp_inst_node.FCreateUserId
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FCreateUserId
     *
     * @param createUserId the value for dp_inst_node.FCreateUserId
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FLastModifyTime
     *
     * @return the value of dp_inst_node.FLastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FLastModifyTime
     *
     * @param lastModifyTime the value for dp_inst_node.FLastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FModifyUserId
     *
     * @return the value of dp_inst_node.FModifyUserId
     *
     * @mbg.generated
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FModifyUserId
     *
     * @param modifyUserId the value for dp_inst_node.FModifyUserId
     *
     * @mbg.generated
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dp_inst_node.FIsdelete
     *
     * @return the value of dp_inst_node.FIsdelete
     *
     * @mbg.generated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dp_inst_node.FIsdelete
     *
     * @param isdelete the value for dp_inst_node.FIsdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NodeInstance other = (NodeInstance) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNodeId() == null ? other.getNodeId() == null : this.getNodeId().equals(other.getNodeId()))
            && (this.getUserDataId() == null ? other.getUserDataId() == null : this.getUserDataId().equals(other.getUserDataId()))
            && (this.getUserAccount() == null ? other.getUserAccount() == null : this.getUserAccount().equals(other.getUserAccount()))
            && (this.getUserIdCard() == null ? other.getUserIdCard() == null : this.getUserIdCard().equals(other.getUserIdCard()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getDeviceFingerprint() == null ? other.getDeviceFingerprint() == null : this.getDeviceFingerprint().equals(other.getDeviceFingerprint()))
            && (this.getParamsJson() == null ? other.getParamsJson() == null : this.getParamsJson().equals(other.getParamsJson()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()))
            && (this.getIsdelete() == null ? other.getIsdelete() == null : this.getIsdelete().equals(other.getIsdelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dp_inst_node
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNodeId() == null) ? 0 : getNodeId().hashCode());
        result = prime * result + ((getUserDataId() == null) ? 0 : getUserDataId().hashCode());
        result = prime * result + ((getUserAccount() == null) ? 0 : getUserAccount().hashCode());
        result = prime * result + ((getUserIdCard() == null) ? 0 : getUserIdCard().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getDeviceFingerprint() == null) ? 0 : getDeviceFingerprint().hashCode());
        result = prime * result + ((getParamsJson() == null) ? 0 : getParamsJson().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        result = prime * result + ((getIsdelete() == null) ? 0 : getIsdelete().hashCode());
        return result;
    }
}