package com.adpanshi.cashloan.dispatch.run.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskInstanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public TaskInstanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("FId is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("FId is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("FId =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("FId <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("FId >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FId >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("FId <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("FId <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("FId in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("FId not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("FId between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FId not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdIsNull() {
            addCriterion("FNodeInstId is null");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdIsNotNull() {
            addCriterion("FNodeInstId is not null");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdEqualTo(Integer value) {
            addCriterion("FNodeInstId =", value, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdNotEqualTo(Integer value) {
            addCriterion("FNodeInstId <>", value, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdGreaterThan(Integer value) {
            addCriterion("FNodeInstId >", value, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FNodeInstId >=", value, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdLessThan(Integer value) {
            addCriterion("FNodeInstId <", value, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdLessThanOrEqualTo(Integer value) {
            addCriterion("FNodeInstId <=", value, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdIn(List<Integer> values) {
            addCriterion("FNodeInstId in", values, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdNotIn(List<Integer> values) {
            addCriterion("FNodeInstId not in", values, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdBetween(Integer value1, Integer value2) {
            addCriterion("FNodeInstId between", value1, value2, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeInstIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FNodeInstId not between", value1, value2, "nodeInstId");
            return (Criteria) this;
        }

        public Criteria andNodeIdIsNull() {
            addCriterion("FNodeId is null");
            return (Criteria) this;
        }

        public Criteria andNodeIdIsNotNull() {
            addCriterion("FNodeId is not null");
            return (Criteria) this;
        }

        public Criteria andNodeIdEqualTo(Integer value) {
            addCriterion("FNodeId =", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotEqualTo(Integer value) {
            addCriterion("FNodeId <>", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdGreaterThan(Integer value) {
            addCriterion("FNodeId >", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FNodeId >=", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLessThan(Integer value) {
            addCriterion("FNodeId <", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdLessThanOrEqualTo(Integer value) {
            addCriterion("FNodeId <=", value, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdIn(List<Integer> values) {
            addCriterion("FNodeId in", values, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotIn(List<Integer> values) {
            addCriterion("FNodeId not in", values, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdBetween(Integer value1, Integer value2) {
            addCriterion("FNodeId between", value1, value2, "nodeId");
            return (Criteria) this;
        }

        public Criteria andNodeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FNodeId not between", value1, value2, "nodeId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("FTaskId is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("FTaskId is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("FTaskId =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("FTaskId <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("FTaskId >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FTaskId >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("FTaskId <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("FTaskId <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("FTaskId in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("FTaskId not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("FTaskId between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FTaskId not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeIsNull() {
            addCriterion("FAdapterCode is null");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeIsNotNull() {
            addCriterion("FAdapterCode is not null");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeEqualTo(String value) {
            addCriterion("FAdapterCode =", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeNotEqualTo(String value) {
            addCriterion("FAdapterCode <>", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeGreaterThan(String value) {
            addCriterion("FAdapterCode >", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FAdapterCode >=", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeLessThan(String value) {
            addCriterion("FAdapterCode <", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeLessThanOrEqualTo(String value) {
            addCriterion("FAdapterCode <=", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeLike(String value) {
            addCriterion("FAdapterCode like", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeNotLike(String value) {
            addCriterion("FAdapterCode not like", value, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeIn(List<String> values) {
            addCriterion("FAdapterCode in", values, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeNotIn(List<String> values) {
            addCriterion("FAdapterCode not in", values, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeBetween(String value1, String value2) {
            addCriterion("FAdapterCode between", value1, value2, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeNotBetween(String value1, String value2) {
            addCriterion("FAdapterCode not between", value1, value2, "adapterCode");
            return (Criteria) this;
        }

        public Criteria andIsSyncIsNull() {
            addCriterion("FIsSync is null");
            return (Criteria) this;
        }

        public Criteria andIsSyncIsNotNull() {
            addCriterion("FIsSync is not null");
            return (Criteria) this;
        }

        public Criteria andIsSyncEqualTo(Boolean value) {
            addCriterion("FIsSync =", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotEqualTo(Boolean value) {
            addCriterion("FIsSync <>", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncGreaterThan(Boolean value) {
            addCriterion("FIsSync >", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsSync >=", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLessThan(Boolean value) {
            addCriterion("FIsSync <", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsSync <=", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncIn(List<Boolean> values) {
            addCriterion("FIsSync in", values, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotIn(List<Boolean> values) {
            addCriterion("FIsSync not in", values, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsSync between", value1, value2, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsSync not between", value1, value2, "isSync");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("FStatus is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("FStatus is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("FStatus =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("FStatus <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("FStatus >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("FStatus >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("FStatus <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("FStatus <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("FStatus in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("FStatus not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("FStatus between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("FStatus not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUserDataIdIsNull() {
            addCriterion("FUserDataId is null");
            return (Criteria) this;
        }

        public Criteria andUserDataIdIsNotNull() {
            addCriterion("FUserDataId is not null");
            return (Criteria) this;
        }

        public Criteria andUserDataIdEqualTo(Integer value) {
            addCriterion("FUserDataId =", value, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdNotEqualTo(Integer value) {
            addCriterion("FUserDataId <>", value, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdGreaterThan(Integer value) {
            addCriterion("FUserDataId >", value, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FUserDataId >=", value, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdLessThan(Integer value) {
            addCriterion("FUserDataId <", value, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdLessThanOrEqualTo(Integer value) {
            addCriterion("FUserDataId <=", value, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdIn(List<Integer> values) {
            addCriterion("FUserDataId in", values, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdNotIn(List<Integer> values) {
            addCriterion("FUserDataId not in", values, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdBetween(Integer value1, Integer value2) {
            addCriterion("FUserDataId between", value1, value2, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserDataIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FUserDataId not between", value1, value2, "userDataId");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNull() {
            addCriterion("FUserMobile is null");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNotNull() {
            addCriterion("FUserMobile is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobileEqualTo(String value) {
            addCriterion("FUserMobile =", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotEqualTo(String value) {
            addCriterion("FUserMobile <>", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThan(String value) {
            addCriterion("FUserMobile >", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThanOrEqualTo(String value) {
            addCriterion("FUserMobile >=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThan(String value) {
            addCriterion("FUserMobile <", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThanOrEqualTo(String value) {
            addCriterion("FUserMobile <=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLike(String value) {
            addCriterion("FUserMobile like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotLike(String value) {
            addCriterion("FUserMobile not like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileIn(List<String> values) {
            addCriterion("FUserMobile in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotIn(List<String> values) {
            addCriterion("FUserMobile not in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileBetween(String value1, String value2) {
            addCriterion("FUserMobile between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotBetween(String value1, String value2) {
            addCriterion("FUserMobile not between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("FUserEmail is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("FUserEmail is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("FUserEmail =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("FUserEmail <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("FUserEmail >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("FUserEmail >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("FUserEmail <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("FUserEmail <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("FUserEmail like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("FUserEmail not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("FUserEmail in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("FUserEmail not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("FUserEmail between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("FUserEmail not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserIdCardIsNull() {
            addCriterion("FUserIdCard is null");
            return (Criteria) this;
        }

        public Criteria andUserIdCardIsNotNull() {
            addCriterion("FUserIdCard is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdCardEqualTo(String value) {
            addCriterion("FUserIdCard =", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardNotEqualTo(String value) {
            addCriterion("FUserIdCard <>", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardGreaterThan(String value) {
            addCriterion("FUserIdCard >", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("FUserIdCard >=", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardLessThan(String value) {
            addCriterion("FUserIdCard <", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardLessThanOrEqualTo(String value) {
            addCriterion("FUserIdCard <=", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardLike(String value) {
            addCriterion("FUserIdCard like", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardNotLike(String value) {
            addCriterion("FUserIdCard not like", value, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardIn(List<String> values) {
            addCriterion("FUserIdCard in", values, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardNotIn(List<String> values) {
            addCriterion("FUserIdCard not in", values, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardBetween(String value1, String value2) {
            addCriterion("FUserIdCard between", value1, value2, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserIdCardNotBetween(String value1, String value2) {
            addCriterion("FUserIdCard not between", value1, value2, "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("FUserName is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("FUserName is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("FUserName =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("FUserName <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("FUserName >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("FUserName >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("FUserName <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("FUserName <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("FUserName like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("FUserName not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("FUserName in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("FUserName not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("FUserName between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("FUserName not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintIsNull() {
            addCriterion("FDeviceFingerprint is null");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintIsNotNull() {
            addCriterion("FDeviceFingerprint is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintEqualTo(String value) {
            addCriterion("FDeviceFingerprint =", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintNotEqualTo(String value) {
            addCriterion("FDeviceFingerprint <>", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintGreaterThan(String value) {
            addCriterion("FDeviceFingerprint >", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintGreaterThanOrEqualTo(String value) {
            addCriterion("FDeviceFingerprint >=", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintLessThan(String value) {
            addCriterion("FDeviceFingerprint <", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintLessThanOrEqualTo(String value) {
            addCriterion("FDeviceFingerprint <=", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintLike(String value) {
            addCriterion("FDeviceFingerprint like", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintNotLike(String value) {
            addCriterion("FDeviceFingerprint not like", value, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintIn(List<String> values) {
            addCriterion("FDeviceFingerprint in", values, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintNotIn(List<String> values) {
            addCriterion("FDeviceFingerprint not in", values, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintBetween(String value1, String value2) {
            addCriterion("FDeviceFingerprint between", value1, value2, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintNotBetween(String value1, String value2) {
            addCriterion("FDeviceFingerprint not between", value1, value2, "deviceFingerprint");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("FCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("FCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("FCreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("FCreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("FCreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FCreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("FCreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("FCreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("FCreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("FCreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("FCreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("FCreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("FCreateUserId is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("FCreateUserId is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("FCreateUserId =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("FCreateUserId <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("FCreateUserId >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FCreateUserId >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("FCreateUserId <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("FCreateUserId <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("FCreateUserId in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("FCreateUserId not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("FCreateUserId between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FCreateUserId not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("FLastModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("FLastModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("FLastModifyTime =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("FLastModifyTime <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("FLastModifyTime >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FLastModifyTime >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("FLastModifyTime <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("FLastModifyTime <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("FLastModifyTime in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("FLastModifyTime not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("FLastModifyTime between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("FLastModifyTime not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNull() {
            addCriterion("FModifyUserId is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIsNotNull() {
            addCriterion("FModifyUserId is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdEqualTo(Integer value) {
            addCriterion("FModifyUserId =", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotEqualTo(Integer value) {
            addCriterion("FModifyUserId <>", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThan(Integer value) {
            addCriterion("FModifyUserId >", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FModifyUserId >=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThan(Integer value) {
            addCriterion("FModifyUserId <", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("FModifyUserId <=", value, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdIn(List<Integer> values) {
            addCriterion("FModifyUserId in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotIn(List<Integer> values) {
            addCriterion("FModifyUserId not in", values, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdBetween(Integer value1, Integer value2) {
            addCriterion("FModifyUserId between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andModifyUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FModifyUserId not between", value1, value2, "modifyUserId");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("FIsdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("FIsdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Boolean value) {
            addCriterion("FIsdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Boolean value) {
            addCriterion("FIsdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Boolean value) {
            addCriterion("FIsdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("FIsdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Boolean value) {
            addCriterion("FIsdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("FIsdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Boolean> values) {
            addCriterion("FIsdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Boolean> values) {
            addCriterion("FIsdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("FIsdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andAdapterCodeLikeInsensitive(String value) {
            addCriterion("upper(FAdapterCode) like", value.toUpperCase(), "adapterCode");
            return (Criteria) this;
        }

        public Criteria andUserMobileLikeInsensitive(String value) {
            addCriterion("upper(FUserMobile) like", value.toUpperCase(), "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserEmailLikeInsensitive(String value) {
            addCriterion("upper(FUserEmail) like", value.toUpperCase(), "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserIdCardLikeInsensitive(String value) {
            addCriterion("upper(FUserIdCard) like", value.toUpperCase(), "userIdCard");
            return (Criteria) this;
        }

        public Criteria andUserNameLikeInsensitive(String value) {
            addCriterion("upper(FUserName) like", value.toUpperCase(), "userName");
            return (Criteria) this;
        }

        public Criteria andDeviceFingerprintLikeInsensitive(String value) {
            addCriterion("upper(FDeviceFingerprint) like", value.toUpperCase(), "deviceFingerprint");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_inst_task
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_inst_task
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}