package com.adpanshi.cashloan.dispatch.userdata.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_name
     *
     * @mbg.generated
     */
    private String login_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_name_email
     *
     * @mbg.generated
     */
    private String login_name_email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_pwd
     *
     * @mbg.generated
     */
    private String login_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.loginpwd_modify_time
     *
     * @mbg.generated
     */
    private Date loginpwd_modify_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.regist_time
     *
     * @mbg.generated
     */
    private Date regist_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.register_client
     *
     * @mbg.generated
     */
    private String register_client;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.trade_pwd
     *
     * @mbg.generated
     */
    private String trade_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.tradepwd_modify_time
     *
     * @mbg.generated
     */
    private Date tradepwd_modify_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.invitation_code
     *
     * @mbg.generated
     */
    private String invitation_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.channel_id
     *
     * @mbg.generated
     */
    private Long channel_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_time
     *
     * @mbg.generated
     */
    private Date login_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.id
     *
     * @return the value of cl_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.id
     *
     * @param id the value for cl_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.uuid
     *
     * @return the value of cl_user.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.uuid
     *
     * @param uuid the value for cl_user.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_name
     *
     * @return the value of cl_user.login_name
     *
     * @mbg.generated
     */
    public String getLogin_name() {
        return login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_name
     *
     * @param login_name the value for cl_user.login_name
     *
     * @mbg.generated
     */
    public void setLogin_name(String login_name) {
        this.login_name = login_name == null ? null : login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_name_email
     *
     * @return the value of cl_user.login_name_email
     *
     * @mbg.generated
     */
    public String getLogin_name_email() {
        return login_name_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_name_email
     *
     * @param login_name_email the value for cl_user.login_name_email
     *
     * @mbg.generated
     */
    public void setLogin_name_email(String login_name_email) {
        this.login_name_email = login_name_email == null ? null : login_name_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_pwd
     *
     * @return the value of cl_user.login_pwd
     *
     * @mbg.generated
     */
    public String getLogin_pwd() {
        return login_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_pwd
     *
     * @param login_pwd the value for cl_user.login_pwd
     *
     * @mbg.generated
     */
    public void setLogin_pwd(String login_pwd) {
        this.login_pwd = login_pwd == null ? null : login_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.loginpwd_modify_time
     *
     * @return the value of cl_user.loginpwd_modify_time
     *
     * @mbg.generated
     */
    public Date getLoginpwd_modify_time() {
        return loginpwd_modify_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.loginpwd_modify_time
     *
     * @param loginpwd_modify_time the value for cl_user.loginpwd_modify_time
     *
     * @mbg.generated
     */
    public void setLoginpwd_modify_time(Date loginpwd_modify_time) {
        this.loginpwd_modify_time = loginpwd_modify_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.regist_time
     *
     * @return the value of cl_user.regist_time
     *
     * @mbg.generated
     */
    public Date getRegist_time() {
        return regist_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.regist_time
     *
     * @param regist_time the value for cl_user.regist_time
     *
     * @mbg.generated
     */
    public void setRegist_time(Date regist_time) {
        this.regist_time = regist_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.register_client
     *
     * @return the value of cl_user.register_client
     *
     * @mbg.generated
     */
    public String getRegister_client() {
        return register_client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.register_client
     *
     * @param register_client the value for cl_user.register_client
     *
     * @mbg.generated
     */
    public void setRegister_client(String register_client) {
        this.register_client = register_client == null ? null : register_client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.trade_pwd
     *
     * @return the value of cl_user.trade_pwd
     *
     * @mbg.generated
     */
    public String getTrade_pwd() {
        return trade_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.trade_pwd
     *
     * @param trade_pwd the value for cl_user.trade_pwd
     *
     * @mbg.generated
     */
    public void setTrade_pwd(String trade_pwd) {
        this.trade_pwd = trade_pwd == null ? null : trade_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.tradepwd_modify_time
     *
     * @return the value of cl_user.tradepwd_modify_time
     *
     * @mbg.generated
     */
    public Date getTradepwd_modify_time() {
        return tradepwd_modify_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.tradepwd_modify_time
     *
     * @param tradepwd_modify_time the value for cl_user.tradepwd_modify_time
     *
     * @mbg.generated
     */
    public void setTradepwd_modify_time(Date tradepwd_modify_time) {
        this.tradepwd_modify_time = tradepwd_modify_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.invitation_code
     *
     * @return the value of cl_user.invitation_code
     *
     * @mbg.generated
     */
    public String getInvitation_code() {
        return invitation_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.invitation_code
     *
     * @param invitation_code the value for cl_user.invitation_code
     *
     * @mbg.generated
     */
    public void setInvitation_code(String invitation_code) {
        this.invitation_code = invitation_code == null ? null : invitation_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.channel_id
     *
     * @return the value of cl_user.channel_id
     *
     * @mbg.generated
     */
    public Long getChannel_id() {
        return channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.channel_id
     *
     * @param channel_id the value for cl_user.channel_id
     *
     * @mbg.generated
     */
    public void setChannel_id(Long channel_id) {
        this.channel_id = channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.level
     *
     * @return the value of cl_user.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.level
     *
     * @param level the value for cl_user.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_time
     *
     * @return the value of cl_user.login_time
     *
     * @mbg.generated
     */
    public Date getLogin_time() {
        return login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_time
     *
     * @param login_time the value for cl_user.login_time
     *
     * @mbg.generated
     */
    public void setLogin_time(Date login_time) {
        this.login_time = login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.state
     *
     * @return the value of cl_user.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.state
     *
     * @param state the value for cl_user.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.remark
     *
     * @return the value of cl_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.remark
     *
     * @param remark the value for cl_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getLogin_name() == null ? other.getLogin_name() == null : this.getLogin_name().equals(other.getLogin_name()))
            && (this.getLogin_name_email() == null ? other.getLogin_name_email() == null : this.getLogin_name_email().equals(other.getLogin_name_email()))
            && (this.getLogin_pwd() == null ? other.getLogin_pwd() == null : this.getLogin_pwd().equals(other.getLogin_pwd()))
            && (this.getLoginpwd_modify_time() == null ? other.getLoginpwd_modify_time() == null : this.getLoginpwd_modify_time().equals(other.getLoginpwd_modify_time()))
            && (this.getRegist_time() == null ? other.getRegist_time() == null : this.getRegist_time().equals(other.getRegist_time()))
            && (this.getRegister_client() == null ? other.getRegister_client() == null : this.getRegister_client().equals(other.getRegister_client()))
            && (this.getTrade_pwd() == null ? other.getTrade_pwd() == null : this.getTrade_pwd().equals(other.getTrade_pwd()))
            && (this.getTradepwd_modify_time() == null ? other.getTradepwd_modify_time() == null : this.getTradepwd_modify_time().equals(other.getTradepwd_modify_time()))
            && (this.getInvitation_code() == null ? other.getInvitation_code() == null : this.getInvitation_code().equals(other.getInvitation_code()))
            && (this.getChannel_id() == null ? other.getChannel_id() == null : this.getChannel_id().equals(other.getChannel_id()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getLogin_time() == null ? other.getLogin_time() == null : this.getLogin_time().equals(other.getLogin_time()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getLogin_name() == null) ? 0 : getLogin_name().hashCode());
        result = prime * result + ((getLogin_name_email() == null) ? 0 : getLogin_name_email().hashCode());
        result = prime * result + ((getLogin_pwd() == null) ? 0 : getLogin_pwd().hashCode());
        result = prime * result + ((getLoginpwd_modify_time() == null) ? 0 : getLoginpwd_modify_time().hashCode());
        result = prime * result + ((getRegist_time() == null) ? 0 : getRegist_time().hashCode());
        result = prime * result + ((getRegister_client() == null) ? 0 : getRegister_client().hashCode());
        result = prime * result + ((getTrade_pwd() == null) ? 0 : getTrade_pwd().hashCode());
        result = prime * result + ((getTradepwd_modify_time() == null) ? 0 : getTradepwd_modify_time().hashCode());
        result = prime * result + ((getInvitation_code() == null) ? 0 : getInvitation_code().hashCode());
        result = prime * result + ((getChannel_id() == null) ? 0 : getChannel_id().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getLogin_time() == null) ? 0 : getLogin_time().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}