package com.adpanshi.cashloan.dispatch.userdata.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andLogin_nameIsNull() {
            addCriterion("login_name is null");
            return (Criteria) this;
        }

        public Criteria andLogin_nameIsNotNull() {
            addCriterion("login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_nameEqualTo(String value) {
            addCriterion("login_name =", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameNotEqualTo(String value) {
            addCriterion("login_name <>", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameGreaterThan(String value) {
            addCriterion("login_name >", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameGreaterThanOrEqualTo(String value) {
            addCriterion("login_name >=", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameLessThan(String value) {
            addCriterion("login_name <", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameLessThanOrEqualTo(String value) {
            addCriterion("login_name <=", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameLike(String value) {
            addCriterion("login_name like", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameNotLike(String value) {
            addCriterion("login_name not like", value, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameIn(List<String> values) {
            addCriterion("login_name in", values, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameNotIn(List<String> values) {
            addCriterion("login_name not in", values, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameBetween(String value1, String value2) {
            addCriterion("login_name between", value1, value2, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_nameNotBetween(String value1, String value2) {
            addCriterion("login_name not between", value1, value2, "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailIsNull() {
            addCriterion("login_name_email is null");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailIsNotNull() {
            addCriterion("login_name_email is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailEqualTo(String value) {
            addCriterion("login_name_email =", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailNotEqualTo(String value) {
            addCriterion("login_name_email <>", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailGreaterThan(String value) {
            addCriterion("login_name_email >", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailGreaterThanOrEqualTo(String value) {
            addCriterion("login_name_email >=", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailLessThan(String value) {
            addCriterion("login_name_email <", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailLessThanOrEqualTo(String value) {
            addCriterion("login_name_email <=", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailLike(String value) {
            addCriterion("login_name_email like", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailNotLike(String value) {
            addCriterion("login_name_email not like", value, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailIn(List<String> values) {
            addCriterion("login_name_email in", values, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailNotIn(List<String> values) {
            addCriterion("login_name_email not in", values, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailBetween(String value1, String value2) {
            addCriterion("login_name_email between", value1, value2, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailNotBetween(String value1, String value2) {
            addCriterion("login_name_email not between", value1, value2, "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdIsNull() {
            addCriterion("login_pwd is null");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdIsNotNull() {
            addCriterion("login_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdEqualTo(String value) {
            addCriterion("login_pwd =", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotEqualTo(String value) {
            addCriterion("login_pwd <>", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdGreaterThan(String value) {
            addCriterion("login_pwd >", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdGreaterThanOrEqualTo(String value) {
            addCriterion("login_pwd >=", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLessThan(String value) {
            addCriterion("login_pwd <", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLessThanOrEqualTo(String value) {
            addCriterion("login_pwd <=", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLike(String value) {
            addCriterion("login_pwd like", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotLike(String value) {
            addCriterion("login_pwd not like", value, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdIn(List<String> values) {
            addCriterion("login_pwd in", values, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotIn(List<String> values) {
            addCriterion("login_pwd not in", values, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdBetween(String value1, String value2) {
            addCriterion("login_pwd between", value1, value2, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdNotBetween(String value1, String value2) {
            addCriterion("login_pwd not between", value1, value2, "login_pwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeIsNull() {
            addCriterion("loginpwd_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeIsNotNull() {
            addCriterion("loginpwd_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeEqualTo(Date value) {
            addCriterion("loginpwd_modify_time =", value, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeNotEqualTo(Date value) {
            addCriterion("loginpwd_modify_time <>", value, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeGreaterThan(Date value) {
            addCriterion("loginpwd_modify_time >", value, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginpwd_modify_time >=", value, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeLessThan(Date value) {
            addCriterion("loginpwd_modify_time <", value, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeLessThanOrEqualTo(Date value) {
            addCriterion("loginpwd_modify_time <=", value, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeIn(List<Date> values) {
            addCriterion("loginpwd_modify_time in", values, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeNotIn(List<Date> values) {
            addCriterion("loginpwd_modify_time not in", values, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeBetween(Date value1, Date value2) {
            addCriterion("loginpwd_modify_time between", value1, value2, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andLoginpwd_modify_timeNotBetween(Date value1, Date value2) {
            addCriterion("loginpwd_modify_time not between", value1, value2, "loginpwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeIsNull() {
            addCriterion("regist_time is null");
            return (Criteria) this;
        }

        public Criteria andRegist_timeIsNotNull() {
            addCriterion("regist_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegist_timeEqualTo(Date value) {
            addCriterion("regist_time =", value, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeNotEqualTo(Date value) {
            addCriterion("regist_time <>", value, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeGreaterThan(Date value) {
            addCriterion("regist_time >", value, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("regist_time >=", value, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeLessThan(Date value) {
            addCriterion("regist_time <", value, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeLessThanOrEqualTo(Date value) {
            addCriterion("regist_time <=", value, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeIn(List<Date> values) {
            addCriterion("regist_time in", values, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeNotIn(List<Date> values) {
            addCriterion("regist_time not in", values, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeBetween(Date value1, Date value2) {
            addCriterion("regist_time between", value1, value2, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegist_timeNotBetween(Date value1, Date value2) {
            addCriterion("regist_time not between", value1, value2, "regist_time");
            return (Criteria) this;
        }

        public Criteria andRegister_clientIsNull() {
            addCriterion("register_client is null");
            return (Criteria) this;
        }

        public Criteria andRegister_clientIsNotNull() {
            addCriterion("register_client is not null");
            return (Criteria) this;
        }

        public Criteria andRegister_clientEqualTo(String value) {
            addCriterion("register_client =", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientNotEqualTo(String value) {
            addCriterion("register_client <>", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientGreaterThan(String value) {
            addCriterion("register_client >", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientGreaterThanOrEqualTo(String value) {
            addCriterion("register_client >=", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientLessThan(String value) {
            addCriterion("register_client <", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientLessThanOrEqualTo(String value) {
            addCriterion("register_client <=", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientLike(String value) {
            addCriterion("register_client like", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientNotLike(String value) {
            addCriterion("register_client not like", value, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientIn(List<String> values) {
            addCriterion("register_client in", values, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientNotIn(List<String> values) {
            addCriterion("register_client not in", values, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientBetween(String value1, String value2) {
            addCriterion("register_client between", value1, value2, "register_client");
            return (Criteria) this;
        }

        public Criteria andRegister_clientNotBetween(String value1, String value2) {
            addCriterion("register_client not between", value1, value2, "register_client");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdIsNull() {
            addCriterion("trade_pwd is null");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdIsNotNull() {
            addCriterion("trade_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdEqualTo(String value) {
            addCriterion("trade_pwd =", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdNotEqualTo(String value) {
            addCriterion("trade_pwd <>", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdGreaterThan(String value) {
            addCriterion("trade_pwd >", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdGreaterThanOrEqualTo(String value) {
            addCriterion("trade_pwd >=", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdLessThan(String value) {
            addCriterion("trade_pwd <", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdLessThanOrEqualTo(String value) {
            addCriterion("trade_pwd <=", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdLike(String value) {
            addCriterion("trade_pwd like", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdNotLike(String value) {
            addCriterion("trade_pwd not like", value, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdIn(List<String> values) {
            addCriterion("trade_pwd in", values, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdNotIn(List<String> values) {
            addCriterion("trade_pwd not in", values, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdBetween(String value1, String value2) {
            addCriterion("trade_pwd between", value1, value2, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdNotBetween(String value1, String value2) {
            addCriterion("trade_pwd not between", value1, value2, "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeIsNull() {
            addCriterion("tradepwd_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeIsNotNull() {
            addCriterion("tradepwd_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeEqualTo(Date value) {
            addCriterion("tradepwd_modify_time =", value, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeNotEqualTo(Date value) {
            addCriterion("tradepwd_modify_time <>", value, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeGreaterThan(Date value) {
            addCriterion("tradepwd_modify_time >", value, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("tradepwd_modify_time >=", value, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeLessThan(Date value) {
            addCriterion("tradepwd_modify_time <", value, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeLessThanOrEqualTo(Date value) {
            addCriterion("tradepwd_modify_time <=", value, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeIn(List<Date> values) {
            addCriterion("tradepwd_modify_time in", values, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeNotIn(List<Date> values) {
            addCriterion("tradepwd_modify_time not in", values, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeBetween(Date value1, Date value2) {
            addCriterion("tradepwd_modify_time between", value1, value2, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andTradepwd_modify_timeNotBetween(Date value1, Date value2) {
            addCriterion("tradepwd_modify_time not between", value1, value2, "tradepwd_modify_time");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeIsNull() {
            addCriterion("invitation_code is null");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeIsNotNull() {
            addCriterion("invitation_code is not null");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeEqualTo(String value) {
            addCriterion("invitation_code =", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotEqualTo(String value) {
            addCriterion("invitation_code <>", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeGreaterThan(String value) {
            addCriterion("invitation_code >", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeGreaterThanOrEqualTo(String value) {
            addCriterion("invitation_code >=", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLessThan(String value) {
            addCriterion("invitation_code <", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLessThanOrEqualTo(String value) {
            addCriterion("invitation_code <=", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLike(String value) {
            addCriterion("invitation_code like", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotLike(String value) {
            addCriterion("invitation_code not like", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeIn(List<String> values) {
            addCriterion("invitation_code in", values, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotIn(List<String> values) {
            addCriterion("invitation_code not in", values, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeBetween(String value1, String value2) {
            addCriterion("invitation_code between", value1, value2, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotBetween(String value1, String value2) {
            addCriterion("invitation_code not between", value1, value2, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andChannel_idIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannel_idIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannel_idEqualTo(Long value) {
            addCriterion("channel_id =", value, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idNotEqualTo(Long value) {
            addCriterion("channel_id <>", value, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idGreaterThan(Long value) {
            addCriterion("channel_id >", value, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idGreaterThanOrEqualTo(Long value) {
            addCriterion("channel_id >=", value, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idLessThan(Long value) {
            addCriterion("channel_id <", value, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idLessThanOrEqualTo(Long value) {
            addCriterion("channel_id <=", value, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idIn(List<Long> values) {
            addCriterion("channel_id in", values, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idNotIn(List<Long> values) {
            addCriterion("channel_id not in", values, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idBetween(Long value1, Long value2) {
            addCriterion("channel_id between", value1, value2, "channel_id");
            return (Criteria) this;
        }

        public Criteria andChannel_idNotBetween(Long value1, Long value2) {
            addCriterion("channel_id not between", value1, value2, "channel_id");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLogin_timeIsNull() {
            addCriterion("login_time is null");
            return (Criteria) this;
        }

        public Criteria andLogin_timeIsNotNull() {
            addCriterion("login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_timeEqualTo(Date value) {
            addCriterion("login_time =", value, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeNotEqualTo(Date value) {
            addCriterion("login_time <>", value, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeGreaterThan(Date value) {
            addCriterion("login_time >", value, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("login_time >=", value, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeLessThan(Date value) {
            addCriterion("login_time <", value, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeLessThanOrEqualTo(Date value) {
            addCriterion("login_time <=", value, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeIn(List<Date> values) {
            addCriterion("login_time in", values, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeNotIn(List<Date> values) {
            addCriterion("login_time not in", values, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeBetween(Date value1, Date value2) {
            addCriterion("login_time between", value1, value2, "login_time");
            return (Criteria) this;
        }

        public Criteria andLogin_timeNotBetween(Date value1, Date value2) {
            addCriterion("login_time not between", value1, value2, "login_time");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUuidLikeInsensitive(String value) {
            addCriterion("upper(uuid) like", value.toUpperCase(), "uuid");
            return (Criteria) this;
        }

        public Criteria andLogin_nameLikeInsensitive(String value) {
            addCriterion("upper(login_name) like", value.toUpperCase(), "login_name");
            return (Criteria) this;
        }

        public Criteria andLogin_name_emailLikeInsensitive(String value) {
            addCriterion("upper(login_name_email) like", value.toUpperCase(), "login_name_email");
            return (Criteria) this;
        }

        public Criteria andLogin_pwdLikeInsensitive(String value) {
            addCriterion("upper(login_pwd) like", value.toUpperCase(), "login_pwd");
            return (Criteria) this;
        }

        public Criteria andRegister_clientLikeInsensitive(String value) {
            addCriterion("upper(register_client) like", value.toUpperCase(), "register_client");
            return (Criteria) this;
        }

        public Criteria andTrade_pwdLikeInsensitive(String value) {
            addCriterion("upper(trade_pwd) like", value.toUpperCase(), "trade_pwd");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLikeInsensitive(String value) {
            addCriterion("upper(invitation_code) like", value.toUpperCase(), "invitation_code");
            return (Criteria) this;
        }

        public Criteria andLevelLikeInsensitive(String value) {
            addCriterion("upper(level) like", value.toUpperCase(), "level");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}